const D=[["Mathematics","Mathematics",.55],["Science","Science",.65],["English","English",.45],["Social Science","Social Science",.60],["Computer","Computer",.50],["Malayalam","Malayalam",.35]];
let books=JSON.parse(localStorage.getItem("sba_books")||"null")||D.map(x=>({name:x[0],subject:x[1],weight:x[2]})),checks=JSON.parse(localStorage.getItem("sba_checks")||"{}"),rems=JSON.parse(localStorage.getItem("sba_rems")||"[]"),bag=JSON.parse(localStorage.getItem("sba_bag")||"null");
const S={Monday:["Mathematics","Science","English","Computer"],Tuesday:["English","Social Science","Mathematics","Malayalam"],Wednesday:["Science","Mathematics","English","Computer"],Thursday:["Social Science","Science","Malayalam","Mathematics"],Friday:["English","Computer","Science","Social Science"]};let day=new Date().toLocaleDateString("en-US",{weekday:"long"});if(!S[day])day="Monday";
const $=x=>document.getElementById(x);function save(){localStorage.setItem("sba_books",JSON.stringify(books));localStorage.setItem("sba_checks",JSON.stringify(checks));localStorage.setItem("sba_rems",JSON.stringify(rems));if(bag)localStorage.setItem("sba_bag",JSON.stringify(bag))}
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");document.querySelectorAll("aside button").forEach(x=>x.classList.toggle("active",x.dataset.p==p));$("title").textContent={home:"Dashboard",pack:"Smart Pack List",table:"Timetable",books:"Books Manager",weight:"Weight Tracker",rem:"Reminders",insight:"Smart Insights"}[p];render()}
document.querySelectorAll("aside button").forEach(x=>x.onclick=()=>go(x.dataset.p));$("theme").onclick=()=>document.body.classList.toggle("dark");
function level(w){return w<.4?["Light","good","🟢"]:w<=.7?["Medium","warn","🟡"]:["Heavy","bad","🔴"]}
function modal(i,t,m){} function closeModal(){}
function renderBooks(){$("bookList").innerHTML=books.map((b,i)=>{let l=level(b.weight);return `<div class="bookrow"><div>${l[2]} <b>${b.name}</b><br><small>${b.subject} · ${b.weight.toFixed(2)} kg</small></div><span class="badge ${l[1]}">${l[0]}</span><button onclick="checkBook(${i})">Check</button><button class="secondary" onclick="delBook(${i})">Delete</button></div>`}).join("")}
function checkBook(i){let b=books[i],l=level(b.weight);if(l[0]=="Heavy")modal("🔴","This book is heavy!",`${b.name} weighs ${b.weight.toFixed(2)} kg. That is above 0.70 kg in this project's example. Consider carrying it only when needed.`);else if(l[0]=="Light")modal("🟢","This book is light!",`${b.name} weighs ${b.weight.toFixed(2)} kg. Great! It is below 0.40 kg in this project's example.`);else modal("🟡","Medium-weight book",`${b.name} weighs ${b.weight.toFixed(2)} kg. It is between 0.40 and 0.70 kg. Keep an eye on your total bag weight.`)}
function delBook(i){books.splice(i,1);save();render()}
$("bookForm").onsubmit=e=>{e.preventDefault();let b={name:$("bn").value,subject:$("bs").value,weight:+$("bw").value};books.push(b);e.target.reset();save();render();checkBook(books.length-1)}
function needed(){return books.filter(b=>S[day].some(s=>b.subject.toLowerCase().includes(s.toLowerCase())||s.toLowerCase().includes(b.subject.toLowerCase())))}
function renderPack(){let a=needed(),done=a.filter(b=>checks[day+b.name]).length,p=a.length?Math.round(done/a.length*100):0,total=a.reduce((x,b)=>x+b.weight,0);$("prog").textContent=p+"%";$("bar").style.width=p+"%";$("pd").textContent=p+"%";$("packList").innerHTML=a.map(b=>{let k=day+b.name,l=level(b.weight);return `<div class="check"><input type="checkbox" ${checks[k]?"checked":""} onchange="toggle('${k.replaceAll("'","\\'")}',this.checked)"><label>${l[2]} <b>${b.name}</b> · ${b.weight.toFixed(2)} kg</label><span class="badge ${l[1]}">${l[0]}</span></div>`}).join("")||"<p>No matching books. Add books first.</p>";$("packSummary").innerHTML=`📦 <b>Today's planned weight:</b> ${total.toFixed(2)} kg · ${done}/${a.length} packed`;$("packTip").innerHTML=total>2.5?"⚠️ <b>Your planned books are quite heavy.</b> Review unnecessary books.":"✅ <b>Good plan!</b> You are packing books connected to today's subjects."}
function toggle(k,v){checks[k]=v;save();renderPack();home()}
function resetPack(){Object.keys(checks).forEach(k=>{if(k.startsWith(day))delete checks[k]});save();renderPack();home()}
function renderTable(){$("days").innerHTML=Object.keys(S).map(d=>`<button class="${d==day?"active":""}" onclick="day='${d}';render()">${d.slice(0,3)}</button>`).join("");$("subjects").innerHTML=S[day].map((s,i)=>`<div><b>Period ${i+1}</b><br>📖 ${s}</div>`).join("")}
function renderWeight(){if(!bag)return;$("result").textContent=bag.w.toFixed(1)+" kg";let lim=bag.b*.1;if(bag.w<=lim){$("wb").textContent="Good weight";$("wb").className="badge good";$("advice").textContent=`Your bag is within the example target of ${lim.toFixed(1)} kg.`}else{$("wb").textContent="Too heavy";$("wb").className="badge bad";$("advice").textContent=`⚠️ Your bag is ${(bag.w-lim).toFixed(1)} kg above the example target. Remove unnecessary items.`}}
$("weightForm").onsubmit=e=>{e.preventDefault();bag={b:+$("body").value,w:+$("bagw").value};save();renderWeight();home();let lim=bag.b*.1;if(bag.w>lim)modal("⚠️","Your bag is too heavy!",`Your bag weighs ${bag.w.toFixed(1)} kg. The simple example target is ${lim.toFixed(1)} kg. Try removing unnecessary items.`);else modal("✅","Your bag looks good!",`Your bag weighs ${bag.w.toFixed(1)} kg and is within the simple example target of ${lim.toFixed(1)} kg.`)}
$("remForm").onsubmit=e=>{e.preventDefault();rems.push({t:$("rt").value,time:$("tm").value});e.target.reset();save();render()}
function renderRem(){ $("rd").textContent=rems.length;$("remList").innerHTML=rems.map((r,i)=>`<div class="remrow">🔔 <b>${r.t}</b> ${r.time||""}<button class="secondary" onclick="rems.splice(${i},1);save();render()">Delete</button></div>`).join("")||"<p>No reminders yet.</p>"}
function home(){let a=needed(),done=a.filter(b=>checks[day+b.name]).length,p=a.length?Math.round(done/a.length*100):0;$("bc").textContent=books.length;$("pd").textContent=p+"%";$("rd").textContent=rems.length;$("classes").innerHTML=S[day].map(s=>`<div class="classrow">📖 ${s}<span>Today</span></div>`).join("");if(bag){let lim=bag.b*.1,ok=bag.w<=lim;$("bd").textContent=bag.w.toFixed(1)+" kg";$("homeStatus").textContent=ok?"Good bag weight":"Too heavy"}}
function insights(){let heavy=books.filter(b=>b.weight>.7),a=needed(),tw=a.reduce((x,b)=>x+b.weight,0);$("ip").textContent=`Today's planned books weigh ${tw.toFixed(2)} kg.`;$("ib").textContent=heavy.length?`${heavy.length} book(s) are heavy.`:"No heavy books in your library.";$("iw").textContent=bag?`Bag: ${bag.w.toFixed(1)} kg; target: ${(bag.b*.1).toFixed(1)} kg.`:"Use Weight Tracker.";$("sum").innerHTML=`📚 ${books.length} books &nbsp; | &nbsp; 🔴 ${heavy.length} heavy &nbsp; | &nbsp; 🎒 ${tw.toFixed(2)} kg today`}
function render(){renderTable();renderBooks();renderPack();renderWeight();renderRem();home();insights()}render();